import type {
    IDataObject,
    IHookFunctions,
    IWebhookFunctions,
    INodeType,
    INodeTypeDescription,
    IWebhookResponseData,
} from 'n8n-workflow';
import { NodeConnectionTypes } from 'n8n-workflow';
import { createHmac } from 'crypto';

export class AllsignTrigger implements INodeType {
    description: INodeTypeDescription = {
        displayName: 'AllSign Trigger',
        name: 'allsignTrigger',
        icon: 'file:allsign.svg',
        group: ['trigger'],
        version: 1,
        subtitle: '={{$parameter["event"]}}',
        description: 'Starts a workflow when an AllSign event occurs (e.g. document signed)',
        defaults: {
            name: 'AllSign Trigger',
        },
        inputs: [],
        outputs: [NodeConnectionTypes.Main],
        credentials: [
            {
                name: 'allSignApi',
                required: true,
            },
        ],
        webhooks: [
            {
                name: 'default',
                httpMethod: 'POST',
                responseMode: 'onReceived',
                path: 'webhook',
            },
        ],
        properties: [
            {
                displayName: 'Event',
                name: 'event',
                type: 'options',
                default: 'document.signed',
                required: true,
                options: [
                    {
                        name: 'Document Completed',
                        value: 'document.completed',
                        description: 'All signers have signed the document',
                    },
                    {
                        name: 'Document Sent',
                        value: 'document.sent',
                        description: 'Document was sent for signing',
                    },
                    {
                        name: 'Document Signed',
                        value: 'document.signed',
                        description: 'A signer has signed the document',
                    },
                    {
                        name: 'Document Voided',
                        value: 'document.voided',
                        description: 'Document was voided/cancelled',
                    },
                ],
                description: 'The AllSign event to listen for',
            },
            {
                displayName: 'Webhook Secret',
                name: 'webhookSecret',
                type: 'string',
                typeOptions: { password: true },
                default: '',
                description: 'Secret key for HMAC signature validation. Found in your AllSign webhook settings.',
            },
        ],
    };

    webhookMethods = {
        default: {
            async checkExists(this: IHookFunctions): Promise<boolean> {
                // AllSign webhooks are configured externally via dashboard
                // This just returns false to ensure the webhook URL is generated
                return false;
            },
            async create(this: IHookFunctions): Promise<boolean> {
                // Webhook URL is generated by n8n and must be configured in AllSign dashboard
                return true;
            },
            async delete(this: IHookFunctions): Promise<boolean> {
                // Cleanup is handled manually in AllSign dashboard
                return true;
            },
        },
    };

    async webhook(this: IWebhookFunctions): Promise<IWebhookResponseData> {
        const req = this.getRequestObject();
        const body = this.getBodyData() as Record<string, unknown>;
        const webhookSecret = this.getNodeParameter('webhookSecret', '') as string;
        const expectedEvent = this.getNodeParameter('event') as string;

        // HMAC signature validation
        if (webhookSecret) {
            const signature = req.headers['x-allsign-signature'] as string;
            if (signature) {
                const rawBody = JSON.stringify(body);
                const computedSignature = createHmac('sha256', webhookSecret)
                    .update(rawBody)
                    .digest('hex');

                if (signature !== computedSignature) {
                    return {
                        noWebhookResponse: true,
                    };
                }
            }
        }

        // Filter by event type if provided in the payload
        const eventType = body.event as string;
        if (eventType && eventType !== expectedEvent) {
            return {
                noWebhookResponse: true,
            };
        }

        return {
            workflowData: [this.helpers.returnJsonArray(body as IDataObject)],
        };
    }
}
